version: "3.6"
services:
  database:
    container_name: "tw_database"
    image: postgres:12.13-alpine
    restart: always
    environment:
      - POSTGRES_USER=pg
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=test
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    logging:
      driver: none
volumes:
  db: