// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type GetUserByID struct {
	ID string `json:"id"`
}

type NewUser struct {
	Name string `json:"name"`
	Age  int    `json:"age"`
}
